#!/usr/bin/env bash
# Determine the reason why your Ubuntu container's Nginx installation is not listening on port 80.
# configuring nginx to run and listen to port 80

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
